package token

import (
	"fmt"
	"strings"
)

type TokenType string

type Token struct {
	Type    TokenType
	Literal string
}

func (t *Token) Debug() string {
	return fmt.Sprintf("Token{Type: %s, Literal: %s}\n", t.Type, t.Literal)
}

const (
	// Special Token
	ILLEGAL       = "ILLEGAL"
	EOF           = "EOF"
	COMMENT_TOKEN = "COMMENT"

	// Token
	IDENTIFIER_TOKEN = "IDENTIFIER"
	KEYWORD_TOKEN    = "KEYWORD"
	NUMBER_TOKEN     = "NUMBER"
	DATETIME_TOKEN   = "DATETIME"
	INTERVAL_TOKEN   = "INTERBAL"

	// Character Token
	SPACE_TOKEN                 = "SPACE ( )"
	DOUBLE_QUOTE_TOKEN          = "DOUBLE QUOTE (\")"
	PERCENT_TOKEN               = "PERCENT (%)"
	AMPERSAND_TOKEN             = "AMPERSAND (&)"
	QUOTE_TOKEN                 = "QUOTE (')"
	LEFT_PAREN_TOKEN            = "LEFT PAREN (()"
	RIGHT_PAREN_TOKEN           = "RIGHT PAREN ())"
	ASTERISK_TOKEN              = "ASTERISK (*)"
	PLUS_SIGN_TOKEN             = "PLUS SIGN (+)"
	COMMA_TOKEN                 = "COMMA (,)"
	MINUS_SIGN_TOKEN            = "MINUS SIGN (-)"
	PERIOD_TOKEN                = "PERIOD (.)"
	SOLIDAS_TOKEN               = "SOLIDAS (/)"
	COLON_TOKEN                 = "COLON (:)"
	SEMICOLON                   = "SEMICOLON (;)"
	LESS_THAN_OPERATOR_TOKEN    = "LESS THAN (<)"
	EQUALS_OPERATOR_TOKEN       = "EQUALS (=)"
	GREATER_THAN_OPERATOR_TOKEN = "GREATER THAN (>)"
	QUESTION_MARK_TOKEN         = "QUESTION MARK (?)"
	UNDERSCORE_TOKEN            = "UNDERSCORE (_)"
	VERTICAL_BAR_TOKEN          = "VERTICAL (|)"
	LEFT_BRACKET_TOKEN          = "LEFT BRACKET ([)"
	RIGHT_BRACKET_TOKEN         = "RIGHT BRACKET (])"

	NOT_EQUALS_OPERATOR_TOKEN             = "NOT EQUALS (<>)"
	GREATER_THAN_OR_EQUALS_OPERATOR_TOKEN = "GREATER THAN OR EQUALS (>=)"
	LESS_THAN_OR_EQUALS_OPERATOR_TOKEN    = "LESS THAN OR EQUALS (<=)"
	CONCATENATION_OPERATOR_TOKEN          = "CONCATENATION (||)"
	DOUBLE_PERIOD_TOKEN                   = "DOUBLE PERIOD (..)"

	// Reserved Keyword
	KEYWORD_ABSOLUTE_TOKEN          = "ABSOLUTE"
	KEYWORD_ACTION_TOKEN            = "ACTION"
	KEYWORD_ADD_TOKEN               = "ADD"
	KEYWORD_ALL_TOKEN               = "ALL"
	KEYWORD_ALLOCATE_TOKEN          = "ALLOCATE"
	KEYWORD_ALTER_TOKEN             = "ALTER"
	KEYWORD_AND_TOKEN               = "AND"
	KEYWORD_ANY_TOKEN               = "ANY"
	KEYWORD_ARE_TOKEN               = "ARE"
	KEYWORD_AS_TOKEN                = "AS"
	KEYWORD_ASC_TOKEN               = "ASC"
	KEYWORD_ASSERTION_TOKEN         = "ASSERTION"
	KEYWORD_AT_TOKEN                = "AT"
	KEYWORD_AUTHORIZATION_TOKEN     = "AUTHORIZATION"
	KEYWORD_AVG_TOKEN               = "AVG"
	KEYWORD_BEGIN_TOKEN             = "BEGIN"
	KEYWORD_BETWEEN_TOKEN           = "BETWEEN"
	KEYWORD_BIT_TOKEN               = "BIT"
	KEYWORD_BIT_LENGTH_TOKEN        = "BIT_LENGTH"
	KEYWORD_BOTH_TOKEN              = "BOTH"
	KEYWORD_BY_TOKEN                = "BY"
	KEYWORD_CASCADE_TOKEN           = "CASCADE"
	KEYWORD_CASCADED_TOKEN          = "CASCADED"
	KEYWORD_CASE_TOKEN              = "CASE"
	KEYWORD_CAST_TOKEN              = "CAST"
	KEYWORD_CATALOG_TOKEN           = "CATALOG"
	KEYWORD_CHAR_TOKEN              = "CHAR"
	KEYWORD_CHARACTER_TOKEN         = "CHARACTER"
	KEYWORD_CHAR_LENGTH_TOKEN       = "CHAR_LENGTH"
	KEYWORD_CHARACTER_LENGTH_TOKEN  = "CHARACTER_LENGTH"
	KEYWORD_CHECK_TOKEN             = "CHECK"
	KEYWORD_CLOSE_TOKEN             = "CLOSE"
	KEYWORD_COALESCE_TOKEN          = "COALESCE"
	KEYWORD_COLLATE_TOKEN           = "COLLATE"
	KEYWORD_COLLATION_TOKEN         = "COLLATION"
	KEYWORD_COLUMN_TOKEN            = "COLUMN"
	KEYWORD_COMMIT_TOKEN            = "COMMIT"
	KEYWORD_CONNECT_TOKEN           = "CONNECT"
	KEYWORD_CONNECTION_TOKEN        = "CONNECTION"
	KEYWORD_CONSTRAINT_TOKEN        = "CONSTRAINT"
	KEYWORD_CONSTRAINTS_TOKEN       = "CONSTRAINTS"
	KEYWORD_CONTINUE_TOKEN          = "CONTINUE"
	KEYWORD_CONVERT_TOKEN           = "CONVERT"
	KEYWORD_CORRESPONDING_TOKEN     = "CORRESPONDING"
	KEYWORD_COUNT_TOKEN             = "COUNT"
	KEYWORD_CREATE_TOKEN            = "CREATE"
	KEYWORD_CROSS_TOKEN             = "CROSS"
	KEYWORD_CURRENT_TOKEN           = "CURRENT"
	KEYWORD_CURRENT_DATE_TOKEN      = "CURRENT_DATE"
	KEYWORD_CURRENT_TIME_TOKEN      = "CURRENT_TIME"
	KEYWORD_CURRENT_TIMESTAMP_TOKEN = "CURRENT_TIMESTAMP"
	KEYWORD_CURRENT_USER_TOKEN      = "CURRENT_USER"
	KEYWORD_CURSOR_TOKEN            = "CURSOR"
	KEYWORD_DATE_TOKEN              = "DATE"
	KEYWORD_DAY_TOKEN               = "DAY"
	KEYWORD_DEALLOCATE_TOKEN        = "DEALLOCATE"
	KEYWORD_DEC_TOKEN               = "DEC"
	KEYWORD_DECIMAL_TOKEN           = "DECIMAL"
	KEYWORD_DECLARE_TOKEN           = "DECLARE"
	KEYWORD_DEFAULT_TOKEN           = "DEFAULT"
	KEYWORD_DEFERRABLE_TOKEN        = "DEFERRABLE"
	KEYWORD_DEFERRED_TOKEN          = "DEFERRED"
	KEYWORD_DELETE_TOKEN            = "DELETE"
	KEYWORD_DESC_TOKEN              = "DESC"
	KEYWORD_DESCRIBE_TOKEN          = "DESCRIBE"
	KEYWORD_DESCRIPTOR_TOKEN        = "DESCRIPTOR"
	KEYWORD_DIAGNOSTICS_TOKEN       = "DIAGNOSTICS"
	KEYWORD_DISCONNECT_TOKEN        = "DISCONNECT"
	KEYWORD_DISTINCT_TOKEN          = "DISTINCT"
	KEYWORD_DOMAIN_TOKEN            = "DOMAIN"
	KEYWORD_DOUBLE_TOKEN            = "DOUBLE"
	KEYWORD_DROP_TOKEN              = "DROP"
	KEYWORD_ELSE_TOKEN              = "ELSE"
	KEYWORD_END_TOKEN               = "END"
	KEYWORD_END_EXEC_TOKEN          = "END-EXEC"
	KEYWORD_ESCAPE_TOKEN            = "ESCAPE"
	KEYWORD_EXCEPT_TOKEN            = "EXCEPT"
	KEYWORD_EXCEPTION_TOKEN         = "EXCEPTION"
	KEYWORD_EXEC_TOKEN              = "EXEC"
	KEYWORD_EXECUTE_TOKEN           = "EXECUTE"
	KEYWORD_EXISTS_TOKEN            = "EXISTS"
	KEYWORD_EXTERNAL_TOKEN          = "EXTERNAL"
	KEYWORD_EXTRACT_TOKEN           = "EXTRACT"
	KEYWORD_FALSE_TOKEN             = "FALSE"
	KEYWORD_FETCH_TOKEN             = "FETCH"
	KEYWORD_FIRST_TOKEN             = "FIRST"
	KEYWORD_FLOAT_TOKEN             = "FLOAT"
	KEYWORD_FOR_TOKEN               = "FOR"
	KEYWORD_FOREIGN_TOKEN           = "FOREIGN"
	KEYWORD_FOUND_TOKEN             = "FOUND"
	KEYWORD_FROM_TOKEN              = "FROM"
	KEYWORD_FULL_TOKEN              = "FULL"
	KEYWORD_GET_TOKEN               = "GET"
	KEYWORD_GLOBAL_TOKEN            = "GLOBAL"
	KEYWORD_GO_TOKEN                = "GO"
	KEYWORD_GOTO_TOKEN              = "GOTO"
	KEYWORD_GRANT_TOKEN             = "GRANT"
	KEYWORD_GROUP_TOKEN             = "GROUP"
	KEYWORD_HAVING_TOKEN            = "HAVING"
	KEYWORD_HOUR_TOKEN              = "HOUR"
	KEYWORD_IDENTITY_TOKEN          = "IDENTITY"
	KEYWORD_IMMEDIATE_TOKEN         = "IMMEDIATE"
	KEYWORD_IN_TOKEN                = "IN"
	KEYWORD_INDICATOR_TOKEN         = "INDICATOR"
	KEYWORD_INITIALLY_TOKEN         = "INITIALLY"
	KEYWORD_INNER_TOKEN             = "INNER"
	KEYWORD_INPUT_TOKEN             = "INPUT"
	KEYWORD_INSENSITIVE_TOKEN       = "INSENSITIVE"
	KEYWORD_INSERT_TOKEN            = "INSERT"
	KEYWORD_INT_TOKEN               = "INT"
	KEYWORD_INTEGER_TOKEN           = "INTEGER"
	KEYWORD_INTERSECT_TOKEN         = "INTERSECT"
	KEYWORD_INTERVAL_TOKEN          = "INTERVAL"
	KEYWORD_INTO_TOKEN              = "INTO"
	KEYWORD_IS_TOKEN                = "IS"
	KEYWORD_ISOLATION_TOKEN         = "ISOLATION"
	KEYWORD_JOIN_TOKEN              = "JOIN"
	KEYWORD_KEY_TOKEN               = "KEY"
	KEYWORD_LANGUAGE_TOKEN          = "LANGUAGE"
	KEYWORD_LAST_TOKEN              = "LAST"
	KEYWORD_LEADING_TOKEN           = "LEADING"
	KEYWORD_LEFT_TOKEN              = "LEFT"
	KEYWORD_LEVEL_TOKEN             = "LEVEL"
	KEYWORD_LIKE_TOKEN              = "LIKE"
	KEYWORD_LOCAL_TOKEN             = "LOCAL"
	KEYWORD_LOWER_TOKEN             = "LOWER"
	KEYWORD_MATCH_TOKEN             = "MATCH"
	KEYWORD_MAX_TOKEN               = "MAX"
	KEYWORD_MIN_TOKEN               = "MIN"
	KEYWORD_MINUTE_TOKEN            = "MINUTE"
	KEYWORD_MODULE_TOKEN            = "MODULE"
	KEYWORD_MONTH_TOKEN             = "MONTH"
	KEYWORD_NAMES_TOKEN             = "NAMES"
	KEYWORD_NATIONAL_TOKEN          = "NATIONAL"
	KEYWORD_NATURAL_TOKEN           = "NATURAL"
	KEYWORD_NCHAR_TOKEN             = "NCHAR"
	KEYWORD_NEXT_TOKEN              = "NEXT"
	KEYWORD_NO_TOKEN                = "NO"
	KEYWORD_NOT_TOKEN               = "NOT"
	KEYWORD_NULL_TOKEN              = "NULL"
	KEYWORD_NULLIF_TOKEN            = "NULLIF"
	KEYWORD_NUMERIC_TOKEN           = "NUMERIC"
	KEYWORD_OCTET_LENGTH_TOKEN      = "OCTET_LENGTH"
	KEYWORD_OF_TOKEN                = "OF"
	KEYWORD_ON_TOKEN                = "ON"
	KEYWORD_ONLY_TOKEN              = "ONLY"
	KEYWORD_OPEN_TOKEN              = "OPEN"
	KEYWORD_OPTION_TOKEN            = "OPTION"
	KEYWORD_OR_TOKEN                = "OR"
	KEYWORD_ORDER_TOKEN             = "ORDER"
	KEYWORD_OUTER_TOKEN             = "OUTER"
	KEYWORD_OUTPUT_TOKEN            = "OUTPUT"
	KEYWORD_OVERLAPS_TOKEN          = "OVERLAPS"
	KEYWORD_PAD_TOKEN               = "PAD"
	KEYWORD_PARTIAL_TOKEN           = "PARTIAL"
	KEYWORD_POSITION_TOKEN          = "POSITION"
	KEYWORD_PRECISION_TOKEN         = "PRECISION"
	KEYWORD_PREPARE_TOKEN           = "PREPARE"
	KEYWORD_PRESERVE_TOKEN          = "PRESERVE"
	KEYWORD_PRIMARY_TOKEN           = "PRIMARY"
	KEYWORD_PRIOR_TOKEN             = "PRIOR"
	KEYWORD_PRIVILEGES_TOKEN        = "PRIVILEGES"
	KEYWORD_PROCEDURE_TOKEN         = "PROCEDURE"
	KEYWORD_PUBLIC_TOKEN            = "PUBLIC"
	KEYWORD_READ_TOKEN              = "READ"
	KEYWORD_REAL_TOKEN              = "REAL"
	KEYWORD_REFERENCES_TOKEN        = "REFERENCES"
	KEYWORD_RELATIVE_TOKEN          = "RELATIVE"
	KEYWORD_RESTRICT_TOKEN          = "RESTRICT"
	KEYWORD_REVOKE_TOKEN            = "REVOKE"
	KEYWORD_RIGHT_TOKEN             = "RIGHT"
	KEYWORD_ROLLBACK_TOKEN          = "ROLLBACK"
	KEYWORD_ROWS_TOKEN              = "ROWS"
	KEYWORD_SCHEMA_TOKEN            = "SCHEMA"
	KEYWORD_SCROLL_TOKEN            = "SCROLL"
	KEYWORD_SECOND_TOKEN            = "SECOND"
	KEYWORD_SECTION_TOKEN           = "SECTION"
	KEYWORD_SELECT_TOKEN            = "SELECT"
	KEYWORD_SESSION_TOKEN           = "SESSION"
	KEYWORD_SESSION_USER_TOKEN      = "SESSION_USER"
	KEYWORD_SET_TOKEN               = "SET"
	KEYWORD_SIZE_TOKEN              = "SIZE"
	KEYWORD_SMALLINT_TOKEN          = "SMALLINT"
	KEYWORD_SOME_TOKEN              = "SOME"
	KEYWORD_SPACE_TOKEN             = "SPACE"
	KEYWORD_SQL_TOKEN               = "SQL"
	KEYWORD_SQLCODE_TOKEN           = "SQLCODE"
	KEYWORD_SQLERROR_TOKEN          = "SQLERROR"
	KEYWORD_SQLSTATE_TOKEN          = "SQLSTATE"
	KEYWORD_SUBSTRING_TOKEN         = "SUBSTRING"
	KEYWORD_SUM_TOKEN               = "SUM"
	KEYWORD_SYSTEM_USER_TOKEN       = "SYSTEM_USER"
	KEYWORD_TABLE_TOKEN             = "TABLE"
	KEYWORD_TEMPORARY_TOKEN         = "TEMPORARY"
	KEYWORD_THEN_TOKEN              = "THEN"
	KEYWORD_TIME_TOKEN              = "TIME"
	KEYWORD_TIMESTAMP_TOKEN         = "TIMESTAMP"
	KEYWORD_TIMEZONE_HOUR_TOKEN     = "TIMEZONE_HOUR"
	KEYWORD_TIMEZONE_MINUTE_TOKEN   = "TIMEZONE_MINUTE"
	KEYWORD_TO_TOKEN                = "TO"
	KEYWORD_TRAILING_TOKEN          = "TRAILING"
	KEYWORD_TRANSACTION_TOKEN       = "TRANSACTION"
	KEYWORD_TRANSLATE_TOKEN         = "TRANSLATE"
	KEYWORD_TRANSLATION_TOKEN       = "TRANSLATION"
	KEYWORD_TRIM_TOKEN              = "TRIM"
	KEYWORD_TRUE_TOKEN              = "TRUE"
	KEYWORD_UNION_TOKEN             = "UNION"
	KEYWORD_UNIQUE_TOKEN            = "UNIQUE"
	KEYWORD_UNKNOWN_TOKEN           = "UNKNOWN"
	KEYWORD_UPDATE_TOKEN            = "UPDATE"
	KEYWORD_UPPER_TOKEN             = "UPPER"
	KEYWORD_USAGE_TOKEN             = "USAGE"
	KEYWORD_USER_TOKEN              = "USER"
	KEYWORD_USING_TOKEN             = "USING"
	KEYWORD_VALUE_TOKEN             = "VALUE"
	KEYWORD_VALUES_TOKEN            = "VALUES"
	KEYWORD_VARCHAR_TOKEN           = "VARCHAR"
	KEYWORD_VARYING_TOKEN           = "VARYING"
	KEYWORD_VIEW_TOKEN              = "VIEW"
	KEYWORD_WHEN_TOKEN              = "WHEN"
	KEYWORD_WHENEVER_TOKEN          = "WHENEVER"
	KEYWORD_WHERE_TOKEN             = "WHERE"
	KEYWORD_WITH_TOKEN              = "WITH"
	KEYWORD_WORK_TOKEN              = "WORK"
	KEYWORD_WRITE_TOKEN             = "WRITE"
	KEYWORD_YEAR_TOKEN              = "YEAR"
	KEYWORD_ZONE_TOKEN              = "ZONE"

	// Non Reserved Keyword
	KEYWORD_ADA_TOKEN                         = "ADA"
	KEYWORD_C_TOKEN                           = "C"
	KEYWORD_CATALOG_NAME_TOKEN                = "CATALOG_NAME"
	KEYWORD_CHARACTER_SET_CATALOG_TOKEN       = "CHARACTER_SET_CATALOG"
	KEYWORD_CHARACTER_SET_NAME_TOKEN          = "CHARACTER_SET_NAME"
	KEYWORD_CHARACTER_SET_SCHEMA_TOKEN        = "CHARACTER_SET_SCHEMA"
	KEYWORD_CLASS_ORIGIN_TOKEN                = "CLASS_ORIGIN"
	KEYWORD_COBOL_TOKEN                       = "COBOL"
	KEYWORD_COLLATION_CATALOG_TOKEN           = "COLLATION_CATALOG"
	KEYWORD_COLLATION_NAME_TOKEN              = "COLLATION_NAME"
	KEYWORD_COLLATION_SCHEMA_TOKEN            = "COLLATION_SCHEMA"
	KEYWORD_COLUMN_NAME_TOKEN                 = "COLUMN_NAME"
	KEYWORD_COMMAND_FUNCTION_TOKEN            = "COMMAND_FUNCTION"
	KEYWORD_COMMITTED_TOKEN                   = "COMMITTED"
	KEYWORD_CONDITION_NUMBER_TOKEN            = "CONDITION_NUMBER"
	KEYWORD_CONNECTION_NAME_TOKEN             = "CONNECTION_NAME"
	KEYWORD_CONSTRAINT_CATALOG_TOKEN          = "CONSTRAINT_CATALOG"
	KEYWORD_CONSTRAINT_NAME_TOKEN             = "CONSTRAINT_NAME"
	KEYWORD_CONSTRAINT_SCHEMA_TOKEN           = "CONSTRAINT_SCHEMA"
	KEYWORD_CURSOR_NAME_TOKEN                 = "CURSOR_NAME"
	KEYWORD_DATA_TOKEN                        = "DATA"
	KEYWORD_DATETIME_INTERVAL_CODE_TOKEN      = "DATETIME_INTERVAL_CODE"
	KEYWORD_DATETIME_INTERVAL_PRECISION_TOKEN = "DATETIME_INTERVAL_PRECISION"
	KEYWORD_DYNAMIC_FUNCTION_TOKEN            = "DYNAMIC_FUNCTION"
	KEYWORD_FORTRAN_TOKEN                     = "FORTRAN"
	KEYWORD_LENGTH_TOKEN                      = "LENGTH"
	KEYWORD_MESSAGE_LENGTH_TOKEN              = "MESSAGE_LENGTH"
	KEYWORD_MESSAGE_OCTET_LENGTH_TOKEN        = "MESSAGE_OCTET_LENGTH"
	KEYWORD_MESSAGE_TEXT_TOKEN                = "MESSAGE_TEXT"
	KEYWORD_MORE_TOKEN                        = "MORE"
	KEYWORD_MUMPS_TOKEN                       = "MUMPS"
	KEYWORD_NAME_TOKEN                        = "NAME"
	KEYWORD_NULLABLE_TOKEN                    = "NULLABLE"
	KEYWORD_NUMBER_TOKEN                      = "NUMBER"
	KEYWORD_PASCAL_TOKEN                      = "PASCAL"
	KEYWORD_PLI_TOKEN                         = "PLI"
	KEYWORD_REPEATABLE_TOKEN                  = "REPEATABLE"
	KEYWORD_RETURNED_LENGTH_TOKEN             = "RETURNED_LENGTH"
	KEYWORD_RETURNED_OCTET_LENGTH_TOKEN       = "RETURNED_OCTET_LENGTH"
	KEYWORD_RETURNED_SQLSTATE_TOKEN           = "RETURNED_SQLSTATE"
	KEYWORD_ROW_COUNT_TOKEN                   = "ROW_COUNT"
	KEYWORD_SCALE_TOKEN                       = "SCALE"
	KEYWORD_SCHEMA_NAME_TOKEN                 = "SCHEMA_NAME"
	KEYWORD_SERIALIZABLE_TOKEN                = "SERIALIZABLE"
	KEYWORD_SERVER_NAME_TOKEN                 = "SERVER_NAME"
	KEYWORD_SUBCLASS_ORIGIN_TOKEN             = "SUBCLASS_ORIGIN"
	KEYWORD_TABLE_NAME_TOKEN                  = "TABLE_NAME"
	KEYWORD_TYPE_TOKEN                        = "TYPE"
	KEYWORD_UNCOMMITTED_TOKEN                 = "UNCOMMITTED"
	KEYWORD_UNNAMED_TOKEN                     = "UNNAMED"
)

var reservedKeyword = map[string]TokenType{
	"ABSOLUTE":          KEYWORD_ABSOLUTE_TOKEN,
	"ACTION":            KEYWORD_ACTION_TOKEN,
	"ADD":               KEYWORD_ADD_TOKEN,
	"ALL":               KEYWORD_ALL_TOKEN,
	"ALLOCATE":          KEYWORD_ALLOCATE_TOKEN,
	"ALTER":             KEYWORD_ALTER_TOKEN,
	"AND":               KEYWORD_AND_TOKEN,
	"ANY":               KEYWORD_ANY_TOKEN,
	"ARE":               KEYWORD_ARE_TOKEN,
	"AS":                KEYWORD_AS_TOKEN,
	"ASC":               KEYWORD_ASC_TOKEN,
	"ASSERTION":         KEYWORD_ASSERTION_TOKEN,
	"AT":                KEYWORD_AT_TOKEN,
	"AUTHORIZATION":     KEYWORD_AUTHORIZATION_TOKEN,
	"AVG":               KEYWORD_AVG_TOKEN,
	"BEGIN":             KEYWORD_BEGIN_TOKEN,
	"BETWEEN":           KEYWORD_BETWEEN_TOKEN,
	"BIT":               KEYWORD_BIT_TOKEN,
	"BIT_LENGTH":        KEYWORD_BIT_LENGTH_TOKEN,
	"BOTH":              KEYWORD_BOTH_TOKEN,
	"BY":                KEYWORD_BY_TOKEN,
	"CASCADE":           KEYWORD_CASCADE_TOKEN,
	"CASCADED":          KEYWORD_CASCADED_TOKEN,
	"CASE":              KEYWORD_CASE_TOKEN,
	"CAST":              KEYWORD_CAST_TOKEN,
	"CATALOG":           KEYWORD_CATALOG_TOKEN,
	"CHAR":              KEYWORD_CHAR_TOKEN,
	"CHARACTER":         KEYWORD_CHARACTER_TOKEN,
	"CHAR_LENGTH":       KEYWORD_CHAR_LENGTH_TOKEN,
	"CHARACTER_LENGTH":  KEYWORD_CHARACTER_LENGTH_TOKEN,
	"CHECK":             KEYWORD_CHECK_TOKEN,
	"CLOSE":             KEYWORD_CLOSE_TOKEN,
	"COALESCE":          KEYWORD_COALESCE_TOKEN,
	"COLLATE":           KEYWORD_COLLATE_TOKEN,
	"COLLATION":         KEYWORD_COLLATION_TOKEN,
	"COLUMN":            KEYWORD_COLUMN_TOKEN,
	"COMMIT":            KEYWORD_COMMIT_TOKEN,
	"CONNECT":           KEYWORD_CONNECT_TOKEN,
	"CONNECTION":        KEYWORD_CONNECTION_TOKEN,
	"CONSTRAINT":        KEYWORD_CONSTRAINT_TOKEN,
	"CONSTRAINTS":       KEYWORD_CONSTRAINTS_TOKEN,
	"CONTINUE":          KEYWORD_CONTINUE_TOKEN,
	"CONVERT":           KEYWORD_CONVERT_TOKEN,
	"CORRESPONDING":     KEYWORD_CORRESPONDING_TOKEN,
	"COUNT":             KEYWORD_COUNT_TOKEN,
	"CREATE":            KEYWORD_CREATE_TOKEN,
	"CROSS":             KEYWORD_CROSS_TOKEN,
	"CURRENT":           KEYWORD_CURRENT_TOKEN,
	"CURRENT_DATE":      KEYWORD_CURRENT_DATE_TOKEN,
	"CURRENT_TIME":      KEYWORD_CURRENT_TIME_TOKEN,
	"CURRENT_TIMESTAMP": KEYWORD_CURRENT_TIMESTAMP_TOKEN,
	"CURRENT_USER":      KEYWORD_CURRENT_USER_TOKEN,
	"CURSOR":            KEYWORD_CURSOR_TOKEN,
	"DATE":              KEYWORD_DATE_TOKEN,
	"DAY":               KEYWORD_DAY_TOKEN,
	"DEALLOCATE":        KEYWORD_DEALLOCATE_TOKEN,
	"DEC":               KEYWORD_DEC_TOKEN,
	"DECIMAL":           KEYWORD_DECIMAL_TOKEN,
	"DECLARE":           KEYWORD_DECLARE_TOKEN,
	"DEFAULT":           KEYWORD_DEFAULT_TOKEN,
	"DEFERRABLE":        KEYWORD_DEFERRABLE_TOKEN,
	"DEFERRED":          KEYWORD_DEFERRED_TOKEN,
	"DELETE":            KEYWORD_DELETE_TOKEN,
	"DESC":              KEYWORD_DESC_TOKEN,
	"DESCRIBE":          KEYWORD_DESCRIBE_TOKEN,
	"DESCRIPTOR":        KEYWORD_DESCRIPTOR_TOKEN,
	"DIAGNOSTICS":       KEYWORD_DIAGNOSTICS_TOKEN,
	"DISCONNECT":        KEYWORD_DISCONNECT_TOKEN,
	"DISTINCT":          KEYWORD_DISTINCT_TOKEN,
	"DOMAIN":            KEYWORD_DOMAIN_TOKEN,
	"DOUBLE":            KEYWORD_DOUBLE_TOKEN,
	"DROP":              KEYWORD_DROP_TOKEN,
	"ELSE":              KEYWORD_ELSE_TOKEN,
	"END":               KEYWORD_END_TOKEN,
	"END-EXEC":          KEYWORD_END_EXEC_TOKEN,
	"ESCAPE":            KEYWORD_ESCAPE_TOKEN,
	"EXCEPT":            KEYWORD_EXCEPT_TOKEN,
	"EXCEPTION":         KEYWORD_EXCEPTION_TOKEN,
	"EXEC":              KEYWORD_EXEC_TOKEN,
	"EXECUTE":           KEYWORD_EXECUTE_TOKEN,
	"EXISTS":            KEYWORD_EXISTS_TOKEN,
	"EXTERNAL":          KEYWORD_EXTERNAL_TOKEN,
	"EXTRACT":           KEYWORD_EXTRACT_TOKEN,
	"FALSE":             KEYWORD_FALSE_TOKEN,
	"FETCH":             KEYWORD_FETCH_TOKEN,
	"FIRST":             KEYWORD_FIRST_TOKEN,
	"FLOAT":             KEYWORD_FLOAT_TOKEN,
	"FOR":               KEYWORD_FOR_TOKEN,
	"FOREIGN":           KEYWORD_FOREIGN_TOKEN,
	"FOUND":             KEYWORD_FOUND_TOKEN,
	"FROM":              KEYWORD_FROM_TOKEN,
	"FULL":              KEYWORD_FULL_TOKEN,
	"GET":               KEYWORD_GET_TOKEN,
	"GLOBAL":            KEYWORD_GLOBAL_TOKEN,
	"GO":                KEYWORD_GO_TOKEN,
	"GOTO":              KEYWORD_GOTO_TOKEN,
	"GRANT":             KEYWORD_GRANT_TOKEN,
	"GROUP":             KEYWORD_GROUP_TOKEN,
	"HAVING":            KEYWORD_HAVING_TOKEN,
	"HOUR":              KEYWORD_HOUR_TOKEN,
	"IDENTITY":          KEYWORD_IDENTITY_TOKEN,
	"IMMEDIATE":         KEYWORD_IMMEDIATE_TOKEN,
	"IN":                KEYWORD_IN_TOKEN,
	"INDICATOR":         KEYWORD_INDICATOR_TOKEN,
	"INITIALLY":         KEYWORD_INITIALLY_TOKEN,
	"INNER":             KEYWORD_INNER_TOKEN,
	"INPUT":             KEYWORD_INPUT_TOKEN,
	"INSENSITIVE":       KEYWORD_INSENSITIVE_TOKEN,
	"INSERT":            KEYWORD_INSERT_TOKEN,
	"INT":               KEYWORD_INT_TOKEN,
	"INTEGER":           KEYWORD_INTEGER_TOKEN,
	"INTERSECT":         KEYWORD_INTERSECT_TOKEN,
	"INTERVAL":          KEYWORD_INTERVAL_TOKEN,
	"INTO":              KEYWORD_INTO_TOKEN,
	"IS":                KEYWORD_IS_TOKEN,
	"ISOLATION":         KEYWORD_ISOLATION_TOKEN,
	"JOIN":              KEYWORD_JOIN_TOKEN,
	"KEY":               KEYWORD_KEY_TOKEN,
	"LANGUAGE":          KEYWORD_LANGUAGE_TOKEN,
	"LAST":              KEYWORD_LAST_TOKEN,
	"LEADING":           KEYWORD_LEADING_TOKEN,
	"LEFT":              KEYWORD_LEFT_TOKEN,
	"LEVEL":             KEYWORD_LEVEL_TOKEN,
	"LIKE":              KEYWORD_LIKE_TOKEN,
	"LOCAL":             KEYWORD_LOCAL_TOKEN,
	"LOWER":             KEYWORD_LOWER_TOKEN,
	"MATCH":             KEYWORD_MATCH_TOKEN,
	"MAX":               KEYWORD_MAX_TOKEN,
	"MIN":               KEYWORD_MIN_TOKEN,
	"MINUTE":            KEYWORD_MINUTE_TOKEN,
	"MODULE":            KEYWORD_MODULE_TOKEN,
	"MONTH":             KEYWORD_MONTH_TOKEN,
	"NAMES":             KEYWORD_NAMES_TOKEN,
	"NATIONAL":          KEYWORD_NATIONAL_TOKEN,
	"NATURAL":           KEYWORD_NATURAL_TOKEN,
	"NCHAR":             KEYWORD_NCHAR_TOKEN,
	"NEXT":              KEYWORD_NEXT_TOKEN,
	"NO":                KEYWORD_NO_TOKEN,
	"NOT":               KEYWORD_NOT_TOKEN,
	"NULL":              KEYWORD_NULL_TOKEN,
	"NULLIF":            KEYWORD_NULLIF_TOKEN,
	"NUMERIC":           KEYWORD_NUMERIC_TOKEN,
	"OCTET_LENGTH":      KEYWORD_OCTET_LENGTH_TOKEN,
	"OF":                KEYWORD_OF_TOKEN,
	"ON":                KEYWORD_ON_TOKEN,
	"ONLY":              KEYWORD_ONLY_TOKEN,
	"OPEN":              KEYWORD_OPEN_TOKEN,
	"OPTION":            KEYWORD_OPTION_TOKEN,
	"OR":                KEYWORD_OR_TOKEN,
	"ORDER":             KEYWORD_ORDER_TOKEN,
	"OUTER":             KEYWORD_OUTER_TOKEN,
	"OUTPUT":            KEYWORD_OUTPUT_TOKEN,
	"OVERLAPS":          KEYWORD_OVERLAPS_TOKEN,
	"PAD":               KEYWORD_PAD_TOKEN,
	"PARTIAL":           KEYWORD_PARTIAL_TOKEN,
	"POSITION":          KEYWORD_POSITION_TOKEN,
	"PRECISION":         KEYWORD_PRECISION_TOKEN,
	"PREPARE":           KEYWORD_PREPARE_TOKEN,
	"PRESERVE":          KEYWORD_PRESERVE_TOKEN,
	"PRIMARY":           KEYWORD_PRIMARY_TOKEN,
	"PRIOR":             KEYWORD_PRIOR_TOKEN,
	"PRIVILEGES":        KEYWORD_PRIVILEGES_TOKEN,
	"PROCEDURE":         KEYWORD_PROCEDURE_TOKEN,
	"PUBLIC":            KEYWORD_PUBLIC_TOKEN,
	"READ":              KEYWORD_READ_TOKEN,
	"REAL":              KEYWORD_REAL_TOKEN,
	"REFERENCES":        KEYWORD_REFERENCES_TOKEN,
	"RELATIVE":          KEYWORD_RELATIVE_TOKEN,
	"RESTRICT":          KEYWORD_RESTRICT_TOKEN,
	"REVOKE":            KEYWORD_REVOKE_TOKEN,
	"RIGHT":             KEYWORD_RIGHT_TOKEN,
	"ROLLBACK":          KEYWORD_ROLLBACK_TOKEN,
	"ROWS":              KEYWORD_ROWS_TOKEN,
	"SCHEMA":            KEYWORD_SCHEMA_TOKEN,
	"SCROLL":            KEYWORD_SCROLL_TOKEN,
	"SECOND":            KEYWORD_SECOND_TOKEN,
	"SECTION":           KEYWORD_SECTION_TOKEN,
	"SELECT":            KEYWORD_SELECT_TOKEN,
	"SESSION":           KEYWORD_SESSION_TOKEN,
	"SESSION_USER":      KEYWORD_SESSION_USER_TOKEN,
	"SET":               KEYWORD_SET_TOKEN,
	"SIZE":              KEYWORD_SIZE_TOKEN,
	"SMALLINT":          KEYWORD_SMALLINT_TOKEN,
	"SOME":              KEYWORD_SOME_TOKEN,
	"SPACE":             KEYWORD_SPACE_TOKEN,
	"SQL":               KEYWORD_SQL_TOKEN,
	"SQLCODE":           KEYWORD_SQLCODE_TOKEN,
	"SQLERROR":          KEYWORD_SQLERROR_TOKEN,
	"SQLSTATE":          KEYWORD_SQLSTATE_TOKEN,
	"SUBSTRING":         KEYWORD_SUBSTRING_TOKEN,
	"SUM":               KEYWORD_SUM_TOKEN,
	"SYSTEM_USER":       KEYWORD_SYSTEM_USER_TOKEN,
	"TABLE":             KEYWORD_TABLE_TOKEN,
	"TEMPORARY":         KEYWORD_TEMPORARY_TOKEN,
	"THEN":              KEYWORD_THEN_TOKEN,
	"TIME":              KEYWORD_TIME_TOKEN,
	"TIMESTAMP":         KEYWORD_TIMESTAMP_TOKEN,
	"TIMEZONE_HOUR":     KEYWORD_TIMEZONE_HOUR_TOKEN,
	"TIMEZONE_MINUTE":   KEYWORD_TIMEZONE_MINUTE_TOKEN,
	"TO":                KEYWORD_TO_TOKEN,
	"TRAILING":          KEYWORD_TRAILING_TOKEN,
	"TRANSACTION":       KEYWORD_TRANSACTION_TOKEN,
	"TRANSLATE":         KEYWORD_TRANSLATE_TOKEN,
	"TRANSLATION":       KEYWORD_TRANSLATION_TOKEN,
	"TRIM":              KEYWORD_TRIM_TOKEN,
	"TRUE":              KEYWORD_TRUE_TOKEN,
	"UNION":             KEYWORD_UNION_TOKEN,
	"UNIQUE":            KEYWORD_UNIQUE_TOKEN,
	"UNKNOWN":           KEYWORD_UNKNOWN_TOKEN,
	"UPDATE":            KEYWORD_UPDATE_TOKEN,
	"UPPER":             KEYWORD_UPPER_TOKEN,
	"USAGE":             KEYWORD_USAGE_TOKEN,
	"USER":              KEYWORD_USER_TOKEN,
	"USING":             KEYWORD_USING_TOKEN,
	"VALUE":             KEYWORD_VALUE_TOKEN,
	"VALUES":            KEYWORD_VALUES_TOKEN,
	"VARCHAR":           KEYWORD_VARCHAR_TOKEN,
	"VARYING":           KEYWORD_VARYING_TOKEN,
	"VIEW":              KEYWORD_VIEW_TOKEN,
	"WHEN":              KEYWORD_WHEN_TOKEN,
	"WHENEVER":          KEYWORD_WHENEVER_TOKEN,
	"WHERE":             KEYWORD_WHERE_TOKEN,
	"WITH":              KEYWORD_WITH_TOKEN,
	"WORK":              KEYWORD_WORK_TOKEN,
	"WRITE":             KEYWORD_WRITE_TOKEN,
	"YEAR":              KEYWORD_YEAR_TOKEN,
	"ZONE":              KEYWORD_ZONE_TOKEN,
}

var nonReservedKeyword = map[string]TokenType{
	"ADA":                         KEYWORD_ADA_TOKEN,
	"C":                           KEYWORD_C_TOKEN,
	"CATALOG_NAME":                KEYWORD_CATALOG_NAME_TOKEN,
	"CHARACTER_SET_CATALOG":       KEYWORD_CHARACTER_SET_CATALOG_TOKEN,
	"CHARACTER_SET_NAME":          KEYWORD_CHARACTER_SET_NAME_TOKEN,
	"CHARACTER_SET_SCHEMA":        KEYWORD_CHARACTER_SET_SCHEMA_TOKEN,
	"CLASS_ORIGIN":                KEYWORD_CLASS_ORIGIN_TOKEN,
	"COBOL":                       KEYWORD_COBOL_TOKEN,
	"COLLATION_CATALOG":           KEYWORD_COLLATION_CATALOG_TOKEN,
	"COLLATION_NAME":              KEYWORD_COLLATION_NAME_TOKEN,
	"COLLATION_SCHEMA":            KEYWORD_COLLATION_SCHEMA_TOKEN,
	"COLUMN_NAME":                 KEYWORD_COLUMN_NAME_TOKEN,
	"COMMAND_FUNCTION":            KEYWORD_COMMAND_FUNCTION_TOKEN,
	"COMMITTED":                   KEYWORD_COMMITTED_TOKEN,
	"CONDITION_NUMBER":            KEYWORD_CONDITION_NUMBER_TOKEN,
	"CONNECTION_NAME":             KEYWORD_CONNECTION_NAME_TOKEN,
	"CONSTRAINT_CATALOG":          KEYWORD_CONSTRAINT_CATALOG_TOKEN,
	"CONSTRAINT_NAME":             KEYWORD_CONSTRAINT_NAME_TOKEN,
	"CONSTRAINT_SCHEMA":           KEYWORD_CONSTRAINT_SCHEMA_TOKEN,
	"CURSOR_NAME":                 KEYWORD_CURSOR_NAME_TOKEN,
	"DATA":                        KEYWORD_DATA_TOKEN,
	"DATETIME_INTERVAL_CODE":      KEYWORD_DATETIME_INTERVAL_CODE_TOKEN,
	"DATETIME_INTERVAL_PRECISION": KEYWORD_DATETIME_INTERVAL_PRECISION_TOKEN,
	"DYNAMIC_FUNCTION":            KEYWORD_DYNAMIC_FUNCTION_TOKEN,
	"FORTRAN":                     KEYWORD_FORTRAN_TOKEN,
	"LENGTH":                      KEYWORD_LENGTH_TOKEN,
	"MESSAGE_LENGTH":              KEYWORD_MESSAGE_LENGTH_TOKEN,
	"MESSAGE_OCTET_LENGTH":        KEYWORD_MESSAGE_OCTET_LENGTH_TOKEN,
	"MESSAGE_TEXT":                KEYWORD_MESSAGE_TEXT_TOKEN,
	"MORE":                        KEYWORD_MORE_TOKEN,
	"MUMPS":                       KEYWORD_MUMPS_TOKEN,
	"NAME":                        KEYWORD_NAME_TOKEN,
	"NULLABLE":                    KEYWORD_NULLABLE_TOKEN,
	"NUMBER":                      KEYWORD_NUMBER_TOKEN,
	"PASCAL":                      KEYWORD_PASCAL_TOKEN,
	"PLI":                         KEYWORD_PLI_TOKEN,
	"REPEATABLE":                  KEYWORD_REPEATABLE_TOKEN,
	"RETURNED_LENGTH":             KEYWORD_RETURNED_LENGTH_TOKEN,
	"RETURNED_OCTET_LENGTH":       KEYWORD_RETURNED_OCTET_LENGTH_TOKEN,
	"RETURNED_SQLSTATE":           KEYWORD_RETURNED_SQLSTATE_TOKEN,
	"ROW_COUNT":                   KEYWORD_ROW_COUNT_TOKEN,
	"SCALE":                       KEYWORD_SCALE_TOKEN,
	"SCHEMA_NAME":                 KEYWORD_SCHEMA_NAME_TOKEN,
	"SERIALIZABLE":                KEYWORD_SERIALIZABLE_TOKEN,
	"SERVER_NAME":                 KEYWORD_SERVER_NAME_TOKEN,
	"SUBCLASS_ORIGIN":             KEYWORD_SUBCLASS_ORIGIN_TOKEN,
	"TABLE_NAME":                  KEYWORD_TABLE_NAME_TOKEN,
	"TYPE":                        KEYWORD_TYPE_TOKEN,
	"UNCOMMITTED":                 KEYWORD_UNCOMMITTED_TOKEN,
	"UNNAMED":                     KEYWORD_UNNAMED_TOKEN,
}

func LookupKeyword(i string) TokenType {
	i = strings.ToUpper(i)
	if tok, ok := reservedKeyword[i]; ok {
		return tok
	}
	if tok, ok := nonReservedKeyword[i]; ok {
		return tok
	}
	return IDENTIFIER_TOKEN
}
